on:
  push:
    branches:
      - master

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: |
          cd EcommerceApp
          mvn clean install

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd EcommerceApp
          mvn sonar:sonar \
            -Dsonar.projectKey=EcommerceApp \
            -Dsonar.host.url=http://34.238.172.73:9000 \
            -Dsonar.login=$SONAR_TOKEN
